# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tab_gui_crawler.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(487, 577)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 471, 541))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 335, 441))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButtonJournal = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButtonJournal.setObjectName("radioButtonJournal")
        self.verticalLayout.addWidget(self.radioButtonJournal)
        self.lineEditJournal = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditJournal.setEnabled(False)
        self.lineEditJournal.setReadOnly(False)
        self.lineEditJournal.setObjectName("lineEditJournal")
        self.verticalLayout.addWidget(self.lineEditJournal)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButtonQuery = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButtonQuery.setChecked(True)
        self.radioButtonQuery.setObjectName("radioButtonQuery")
        self.verticalLayout_2.addWidget(self.radioButtonQuery)
        self.textEditQuery = QtWidgets.QTextEdit(self.layoutWidget)
        self.textEditQuery.setObjectName("textEditQuery")
        self.verticalLayout_2.addWidget(self.textEditQuery)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.labelOutputPath = QtWidgets.QLabel(self.layoutWidget)
        self.labelOutputPath.setObjectName("labelOutputPath")
        self.verticalLayout_4.addWidget(self.labelOutputPath)
        self.lineEditOutputPath = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditOutputPath.setObjectName("lineEditOutputPath")
        self.verticalLayout_4.addWidget(self.lineEditOutputPath)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_7.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBoxDocumentType = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBoxDocumentType.setObjectName("comboBoxDocumentType")
        self.comboBoxDocumentType.addItem("")
        self.comboBoxDocumentType.addItem("")
        self.comboBoxDocumentType.addItem("")
        self.comboBoxDocumentType.addItem("")
        self.comboBoxDocumentType.addItem("")
        self.comboBoxDocumentType.addItem("")
        self.comboBoxDocumentType.addItem("")
        self.comboBoxDocumentType.addItem("")
        self.comboBoxDocumentType.addItem("")
        self.comboBoxDocumentType.addItem("")
        self.comboBoxDocumentType.addItem("")
        self.comboBoxDocumentType.addItem("")
        self.comboBoxDocumentType.addItem("")
        self.comboBoxDocumentType.addItem("")
        self.comboBoxDocumentType.addItem("")
        self.comboBoxDocumentType.addItem("")
        self.comboBoxDocumentType.addItem("")
        self.comboBoxDocumentType.addItem("")
        self.comboBoxDocumentType.addItem("")
        self.comboBoxDocumentType.addItem("")
        self.comboBoxDocumentType.addItem("")
        self.comboBoxDocumentType.addItem("")
        self.comboBoxDocumentType.addItem("")
        self.comboBoxDocumentType.addItem("")
        self.comboBoxDocumentType.addItem("")
        self.comboBoxDocumentType.addItem("")
        self.comboBoxDocumentType.addItem("")
        self.comboBoxDocumentType.addItem("")
        self.comboBoxDocumentType.addItem("")
        self.comboBoxDocumentType.addItem("")
        self.comboBoxDocumentType.addItem("")
        self.comboBoxDocumentType.addItem("")
        self.comboBoxDocumentType.addItem("")
        self.comboBoxDocumentType.addItem("")
        self.comboBoxDocumentType.addItem("")
        self.comboBoxDocumentType.addItem("")
        self.comboBoxDocumentType.addItem("")
        self.comboBoxDocumentType.addItem("")
        self.comboBoxDocumentType.addItem("")
        self.comboBoxDocumentType.addItem("")
        self.comboBoxDocumentType.addItem("")
        self.comboBoxDocumentType.addItem("")
        self.comboBoxDocumentType.addItem("")
        self.horizontalLayout.addWidget(self.comboBoxDocumentType)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.comboBoxOutputFormat = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBoxOutputFormat.setObjectName("comboBoxOutputFormat")
        self.comboBoxOutputFormat.addItem("")
        self.comboBoxOutputFormat.addItem("")
        self.comboBoxOutputFormat.addItem("")
        self.comboBoxOutputFormat.addItem("")
        self.comboBoxOutputFormat.addItem("")
        self.comboBoxOutputFormat.addItem("")
        self.comboBoxOutputFormat.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBoxOutputFormat)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.progressBarDownload = QtWidgets.QProgressBar(self.layoutWidget)
        self.progressBarDownload.setProperty("value", 0)
        self.progressBarDownload.setTextVisible(True)
        self.progressBarDownload.setOrientation(QtCore.Qt.Horizontal)
        self.progressBarDownload.setInvertedAppearance(False)
        self.progressBarDownload.setObjectName("progressBarDownload")
        self.verticalLayout_7.addWidget(self.progressBarDownload)
        self.pushButtonJournal = QtWidgets.QPushButton(self.tab)
        self.pushButtonJournal.setEnabled(False)
        self.pushButtonJournal.setGeometry(QtCore.QRect(360, 40, 99, 28))
        self.pushButtonJournal.setObjectName("pushButtonJournal")
        self.pushButtonOutputPath = QtWidgets.QPushButton(self.tab)
        self.pushButtonOutputPath.setEnabled(True)
        self.pushButtonOutputPath.setGeometry(QtCore.QRect(360, 330, 99, 28))
        self.pushButtonOutputPath.setObjectName("pushButtonOutputPath")
        self.pushButtonStartCrawler = QtWidgets.QPushButton(self.tab)
        self.pushButtonStartCrawler.setEnabled(False)
        self.pushButtonStartCrawler.setGeometry(QtCore.QRect(190, 460, 99, 28))
        self.pushButtonStartCrawler.setObjectName("pushButtonStartCrawler")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 442, 101))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_8.addWidget(self.label_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioButtonPlaintext = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButtonPlaintext.setChecked(True)
        self.radioButtonPlaintext.setObjectName("radioButtonPlaintext")
        self.horizontalLayout_3.addWidget(self.radioButtonPlaintext)
        self.radioButtonBibtex = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButtonBibtex.setObjectName("radioButtonBibtex")
        self.horizontalLayout_3.addWidget(self.radioButtonBibtex)
        self.radioButtonXML = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButtonXML.setObjectName("radioButtonXML")
        self.horizontalLayout_3.addWidget(self.radioButtonXML)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEditParsrInputPath = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEditParsrInputPath.setObjectName("lineEditParsrInputPath")
        self.horizontalLayout_4.addWidget(self.lineEditParsrInputPath)
        self.pushButtonParserInput = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButtonParserInput.setObjectName("pushButtonParserInput")
        self.horizontalLayout_4.addWidget(self.pushButtonParserInput)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        self.pushButtonParserStart = QtWidgets.QPushButton(self.tab_2)
        self.pushButtonParserStart.setEnabled(False)
        self.pushButtonParserStart.setGeometry(QtCore.QRect(190, 400, 93, 28))
        self.pushButtonParserStart.setObjectName("pushButtonParserStart")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 120, 442, 251))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_9.addWidget(self.label_4)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.radioButtonSQLite = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButtonSQLite.setChecked(True)
        self.radioButtonSQLite.setObjectName("radioButtonSQLite")
        self.verticalLayout_11.addWidget(self.radioButtonSQLite)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lineEditParsrSQLiteOutput = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEditParsrSQLiteOutput.setObjectName("lineEditParsrSQLiteOutput")
        self.horizontalLayout_6.addWidget(self.lineEditParsrSQLiteOutput)
        self.pushButtonParserSQLiteOutput = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButtonParserSQLiteOutput.setObjectName("pushButtonParserSQLiteOutput")
        self.horizontalLayout_6.addWidget(self.pushButtonParserSQLiteOutput)
        self.verticalLayout_11.addLayout(self.horizontalLayout_6)
        self.verticalLayout_9.addLayout(self.verticalLayout_11)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.radioButtonMySQL = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButtonMySQL.setObjectName("radioButtonMySQL")
        self.horizontalLayout_8.addWidget(self.radioButtonMySQL)
        self.verticalLayout_10.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_7.setEnabled(True)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_11.addWidget(self.label_7)
        self.lineEditParsrMySQLDBAddress = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEditParsrMySQLDBAddress.setEnabled(False)
        self.lineEditParsrMySQLDBAddress.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEditParsrMySQLDBAddress.setObjectName("lineEditParsrMySQLDBAddress")
        self.horizontalLayout_11.addWidget(self.lineEditParsrMySQLDBAddress)
        self.verticalLayout_10.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_8.setEnabled(True)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_13.addWidget(self.label_8)
        self.lineEditParsrMySQLDBName = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEditParsrMySQLDBName.setEnabled(False)
        self.lineEditParsrMySQLDBName.setText("")
        self.lineEditParsrMySQLDBName.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEditParsrMySQLDBName.setObjectName("lineEditParsrMySQLDBName")
        self.horizontalLayout_13.addWidget(self.lineEditParsrMySQLDBName)
        self.verticalLayout_10.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_9.addWidget(self.label_5)
        self.lineEditParsrMySQLUsername = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEditParsrMySQLUsername.setEnabled(False)
        self.lineEditParsrMySQLUsername.setObjectName("lineEditParsrMySQLUsername")
        self.horizontalLayout_9.addWidget(self.lineEditParsrMySQLUsername)
        self.verticalLayout_10.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_10.addWidget(self.label_6)
        self.lineEditParsrMySQLPassword = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEditParsrMySQLPassword.setEnabled(False)
        self.lineEditParsrMySQLPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditParsrMySQLPassword.setObjectName("lineEditParsrMySQLPassword")
        self.horizontalLayout_10.addWidget(self.lineEditParsrMySQLPassword)
        self.verticalLayout_10.addLayout(self.horizontalLayout_10)
        self.verticalLayout_9.addLayout(self.verticalLayout_10)
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 487, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionWeb_of_Science = QtWidgets.QAction(MainWindow)
        self.actionWeb_of_Science.setObjectName("actionWeb_of_Science")
        self.actionCNKI = QtWidgets.QAction(MainWindow)
        self.actionCNKI.setObjectName("actionCNKI")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Web of Science Crawler"))
        self.radioButtonJournal.setText(_translate("MainWindow", "期刊列表爬取"))
        self.radioButtonQuery.setText(_translate("MainWindow", "高级检索式爬取"))
        self.labelOutputPath.setText(_translate("MainWindow", "保存路径"))
        self.label.setText(_translate("MainWindow", "文献类型"))
        self.comboBoxDocumentType.setItemText(0, _translate("MainWindow", "All document types"))
        self.comboBoxDocumentType.setItemText(1, _translate("MainWindow", "Article"))
        self.comboBoxDocumentType.setItemText(2, _translate("MainWindow", "Abstract of Published Item"))
        self.comboBoxDocumentType.setItemText(3, _translate("MainWindow", "Art Exhibit Review"))
        self.comboBoxDocumentType.setItemText(4, _translate("MainWindow", "Bibliography"))
        self.comboBoxDocumentType.setItemText(5, _translate("MainWindow", "Biographical-Item"))
        self.comboBoxDocumentType.setItemText(6, _translate("MainWindow", "Book"))
        self.comboBoxDocumentType.setItemText(7, _translate("MainWindow", "Book Chapter"))
        self.comboBoxDocumentType.setItemText(8, _translate("MainWindow", "Book Review"))
        self.comboBoxDocumentType.setItemText(9, _translate("MainWindow", "Chronology"))
        self.comboBoxDocumentType.setItemText(10, _translate("MainWindow", "Correction"))
        self.comboBoxDocumentType.setItemText(11, _translate("MainWindow", "Correction, Addition"))
        self.comboBoxDocumentType.setItemText(12, _translate("MainWindow", "Dance Performance Review"))
        self.comboBoxDocumentType.setItemText(13, _translate("MainWindow", "Data Paper"))
        self.comboBoxDocumentType.setItemText(14, _translate("MainWindow", "Database Review"))
        self.comboBoxDocumentType.setItemText(15, _translate("MainWindow", "Discussion"))
        self.comboBoxDocumentType.setItemText(16, _translate("MainWindow", "Early Access"))
        self.comboBoxDocumentType.setItemText(17, _translate("MainWindow", "Editorial Material"))
        self.comboBoxDocumentType.setItemText(18, _translate("MainWindow", "Excerpt"))
        self.comboBoxDocumentType.setItemText(19, _translate("MainWindow", "Fiction, Creative Prose"))
        self.comboBoxDocumentType.setItemText(20, _translate("MainWindow", "Film Review"))
        self.comboBoxDocumentType.setItemText(21, _translate("MainWindow", "Hardware Review"))
        self.comboBoxDocumentType.setItemText(22, _translate("MainWindow", "Item About an Individual"))
        self.comboBoxDocumentType.setItemText(23, _translate("MainWindow", "Letter"))
        self.comboBoxDocumentType.setItemText(24, _translate("MainWindow", "Meeting Abstract"))
        self.comboBoxDocumentType.setItemText(25, _translate("MainWindow", "Meeting Summary"))
        self.comboBoxDocumentType.setItemText(26, _translate("MainWindow", "Music Performance Review"))
        self.comboBoxDocumentType.setItemText(27, _translate("MainWindow", "Music Score"))
        self.comboBoxDocumentType.setItemText(28, _translate("MainWindow", "Music Score Review"))
        self.comboBoxDocumentType.setItemText(29, _translate("MainWindow", "News Item"))
        self.comboBoxDocumentType.setItemText(30, _translate("MainWindow", "Note"))
        self.comboBoxDocumentType.setItemText(31, _translate("MainWindow", "Poetry"))
        self.comboBoxDocumentType.setItemText(32, _translate("MainWindow", "Proceedings Paper"))
        self.comboBoxDocumentType.setItemText(33, _translate("MainWindow", "Record Review"))
        self.comboBoxDocumentType.setItemText(34, _translate("MainWindow", "Reprint"))
        self.comboBoxDocumentType.setItemText(35, _translate("MainWindow", "Retracted Publication"))
        self.comboBoxDocumentType.setItemText(36, _translate("MainWindow", "Retraction"))
        self.comboBoxDocumentType.setItemText(37, _translate("MainWindow", "Review"))
        self.comboBoxDocumentType.setItemText(38, _translate("MainWindow", "Script"))
        self.comboBoxDocumentType.setItemText(39, _translate("MainWindow", "Software Review"))
        self.comboBoxDocumentType.setItemText(40, _translate("MainWindow", "TV Review, Radio Review"))
        self.comboBoxDocumentType.setItemText(41, _translate("MainWindow", "TV Review, Radio Review Video"))
        self.comboBoxDocumentType.setItemText(42, _translate("MainWindow", "Theater Review"))
        self.label_2.setText(_translate("MainWindow", "保存格式"))
        self.comboBoxOutputFormat.setItemText(0, _translate("MainWindow", "Plain Text"))
        self.comboBoxOutputFormat.setItemText(1, _translate("MainWindow", "Bibtex"))
        self.comboBoxOutputFormat.setItemText(2, _translate("MainWindow", "HTML"))
        self.comboBoxOutputFormat.setItemText(3, _translate("MainWindow", "Tab-delimited (Win)"))
        self.comboBoxOutputFormat.setItemText(4, _translate("MainWindow", "Tab-delimited (Mac)"))
        self.comboBoxOutputFormat.setItemText(5, _translate("MainWindow", "Tab-delimited (Win, UTF-8)"))
        self.comboBoxOutputFormat.setItemText(6, _translate("MainWindow", "Tab-delimited (Mac, UTF-8)"))
        self.pushButtonJournal.setText(_translate("MainWindow", "选择期刊列表"))
        self.pushButtonOutputPath.setText(_translate("MainWindow", "选择保存路径"))
        self.pushButtonStartCrawler.setText(_translate("MainWindow", "开始爬取"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Crawler"))
        self.label_3.setText(_translate("MainWindow", "请选择需要解析的文件格式"))
        self.radioButtonPlaintext.setText(_translate("MainWindow", "Plain Text"))
        self.radioButtonBibtex.setText(_translate("MainWindow", "Bibtex"))
        self.radioButtonXML.setText(_translate("MainWindow", "XML"))
        self.pushButtonParserInput.setText(_translate("MainWindow", "选择文件目录"))
        self.pushButtonParserStart.setText(_translate("MainWindow", "开始解析"))
        self.label_4.setText(_translate("MainWindow", "请选择解析结果存放形式"))
        self.radioButtonSQLite.setText(_translate("MainWindow", "SQLite"))
        self.pushButtonParserSQLiteOutput.setText(_translate("MainWindow", "选择导出目录"))
        self.radioButtonMySQL.setText(_translate("MainWindow", "MySQL"))
        self.label_7.setText(_translate("MainWindow", "主 机 地 址："))
        self.lineEditParsrMySQLDBAddress.setText(_translate("MainWindow", "localhost"))
        self.label_8.setText(_translate("MainWindow", "数 据 库 名："))
        self.label_5.setText(_translate("MainWindow", "用   户  名："))
        self.label_6.setText(_translate("MainWindow", "密       码："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Parser"))
        self.actionWeb_of_Science.setText(_translate("MainWindow", "Web of Science"))
        self.actionCNKI.setText(_translate("MainWindow", "CNKI"))

